mapping = {
    "2nd Neurology Clinic UN Bratislava": 1262,
    "II.neurologická klinika LFUK a UN Bratislava": 1262,
    "Center for Interventional Neuroradiology and Endovascular Care": 402,
    "Centrum intervenčnej neuroradiológie a endovaskulárnej liečby": 402,
    "Central military faculty hospital Ruzomberok": 1488,
    "Ústredná vojenská nemocnica SNP Ružomberok - Fakultná Nemocnica": 1488,
    "Dolnooravska Hospital Dolny Kubin": 1514,
    "Dolnooravská Nemocnica s poliklinikou Dolný Kubín": 1514,
    "Faculty Hospital Banska Bystrica": 1477,
    "Fakultná nemocnica s poliklinikou F.D.Roosevelta Banská Bystrica": 1477,
    "Faculty Hospital Nitra": 1482,
    "Fakultná nemocnica Nitra": 1482,
    "Faculty Hospital Trnava": 1478,
    "Fakultná nemocnica Trnava": 1478,
    "Faculty Hospital and Policlinic of Zilina": 1270,
    "Fakultná nemocnica s poliklinikou Žilina": 1270,
    "Faculty Hospital of J. A. Reiman, Presov": 1264,
    "Fakultná nemocnica Jána Adama Reimana Prešov": 1264,
    "Faculty hospital AGEL Skalica": 1497,
    "FN AGEL Skalica": 1497,
    "Faculty hospital Trenčín": 1480,
    "Fakultná nemocnica Trenčín": 1480,
    "Faculty hospital with polyclinic Nové Zámky": 1297,
    "Fakultná nemocnica s poliklinikou Nové Zámky": 1297,
    "General Hospital Velky Krtis": 1487,
    "Všeobecná nemocnica s poliklinikou Veľký Krtíš": 1487,
    "General hospital Rimavska Sobota": 1507,
    "Všeobecná nemocnica Rimavská Sobota": 1507,
    "General hospital with policlinic Lučenec": 1286,
    "Všeobecná nemocnica s poliklinikou Lučenec": 1286,
    "Hospita Agel Levice": 1280,
    "Nemocnica Agel Levice": 1280,
    "Hospital A. Lena, Humenne": 1504,
    "Nemocnica A. Leňa, Humenné": 1504,
    "Hospital Agel Banska Stiavnica": 1563,
    "Nemocnica AGEL Banská Štiavnica": 1563,
    "Hospital Agel Levoca a.s.": 1263,
    "Nemocnica Agel Levoča a.s.": 1263,
    "Hospital Bory Bratislava": 1506,
    "Nemocnica Bory Bratislava": 1506,
    "Hospital Brezno": 1486,
    "Nemocnica s poliklinikou Brezno": 1486,
    "Hospital Dunajska Streda": 1498,
    "Nemocnica s poliklinikou Dunajská Streda": 1498,
    "Hospital Kosice - Saca": 1490,
    "Nemocnica Agel Košice - Šaca": 1490,
    "Hospital Kralovsky Chlmec": 1502,
    "Nemocnica s poliklinikou Kráľovský Chlmec": 1502,
    "Hospital Krupina": 1500,
    "Nemocnica Agel Krupina": 1500,
    "Hospital Partizanske": 1501,
    "Nemocnica na okraji mesta, Partizánske": 1501,
    "Hospital Penta Hospitals Spisska Nova Ves": 1492,
    "Nemocnica Penta Hospitals Spišská Nová ve": 1492,
    "Hospital Podunajske Biskupice": 1483,
    "Geriatrická nemocnica Bratislava Podunajské Biskupice": 1483,
    "Hospital Poprad": 1271,
    "Nemocnica Poprad a.s.": 1271,
    "Hospital Povazska Bystrica": 1479,
    "Nemocnica s poliklinikou Považská Bystrica": 1479,
    "Hospital Prievidza - Bojnice": 1481,
    "Nemocnica s poliklinikou Prievidza so sídlom v Bojniciach": 1481,
    "Hospital St. Jacob, Bardejov": 1489,
    "Nemocnica s poliklinikou Sv. Jakuba, Bardejov": 1489,
    "Hospital Stara Lubovna": 1495,
    "Ľubovnianska nemocnica": 1495,
    "Hospital Topolcany": 1503,
    "Nemocnica Topoľčany": 1503,
    "Hospital Trebisov": 1493,
    "Nemocnica s poliklinikou Trebišov": 1493,
    "Hospital Ziar nad Hronom": 1508,
    "Nemocnica Žiar nad Hronom": 1508,
    "Hospital Zvolen": 1499,
    "Nemocnica Agel Zvolen": 1499,
    "Hospital of army general L. Svoboda, Svidnik": 1505,
    "Nemocnica Arm. Generála L. Svobodu Svidník": 1505,
    "KNsP Cadca": 1364,
    "Liptov Hospital": 1268,
    "Liptovská nemocnica s poliklinikou MUDr. Ivana Stodolu": 1268,
    "Nemocnica Agel Komárno s.r.o.": 1310,
    "Penta Hospitals - Hospital Rožňava": 1491,
    "Penta hospitals - Nemocnica Rožňava": 1491,
    "St. Lukas Hospital Galanta": 1284,
    "Nemocnica s poliklinikou Sv. Lukáša Galanta": 1284,
    "The hospital of S. Kukura Michalovce": 1318,
    "Nemocnica s poliklinikou Š. Kukuru Michalovce": 1318,
    "University Hospital Bratislava - Ruzinov": 1275,
    "UNIVERZITNÁ NEMOCNICA BRATISLAVA - NEMOCNICA RUŽINOV": 1275,
    "University Hospital Bratislava, Hospital st. Cyrila a Metoda": 1485,
    "UN Bratislava, Nemocnica sv. Cyrila a Metoda": 1485,
    "University Hospital L. Pasteur Kosice": 1258,
    "Univerzitná nemocnica L. Pasteura Kosice": 1258,
    "University hospital Martin": 1300,
    "Univerzitná nemocnica Martin": 1300,
    "University hospital Bratislava - Old town": 1484,
    "Univerzitná nemocnica Bratislava -  Nemocnica Staré Mesto": 1484,
    "VUSCH Kosice": 1494,
    "VÚSCH Košice": 1494,
    "Vranovska nemocnica": 1272,
    "Vranovská nemocnica a.s.": 1272,
}
